# Generated by Django 5.0 on 2024-01-03 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automatic_purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmemailtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirm_email_tokens",
                to="automatic_purchases.usercontact",
                verbose_name="The User which is associated to this password reset token",
            ),
        ),
    ]
